spring:
  application:
    name: City SMS Service
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m

server:
  port: 8080

sms:
  service:
    secret: "VGhpc0lzQVNlY3JldEtleUZvck15Q2l0eUdvdlNtc1NlcnZpY2UyMDI0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
