spring:
  application:
    name: City SMS Service
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m

server:
  port: 8080

sms:
  service:
    secret: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJteWNpdHlnb3Ytc3lzdGVtIn0.l-3f3u6G7q3T5y-k6K4k6J4k6I4k6H4k6G4k6F4k6E4"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
