spring:
  application:
    name: MyCityGov

  datasource:
    # Connect to Postgres running in container "db"
    url: jdbc:postgresql://db:5432/municipality_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: <username> # TODO put mailtrap mail and password
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    issuer: "my-city-gov-api"
    audience: "my-city-gov-app"
    secret: "MIA_POLY_MEGALI_MISTIKI_FRASE_GIA_TO_SIGNATURE_TOY_TOKEN_PREPEI_NA_EINAI_LARGE"
    ttl-minutes: 60