spring:
  application:
    name: MyCityGov

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    # Connect to Postgres running in container "db"
    url: jdbc:postgresql://db:5432/municipality_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

sms:
  service:
    url: ${SMS_SERVICE_URL:http://localhost:8081}
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteWNpdHlnb3Ytc3lzdGVtIn0.IqnQSvplQROn1VaGNkRlvvL-s-5fM2XjIwLzc-Gsw5k"

app:
  jwt:
    issuer: "my-city-gov-api"
    audience: "my-city-gov-app"
    secret: "MIA_POLY_MEGALI_MISTIKI_FRASE_GIA_TO_SIGNATURE_TOY_TOKEN_PREPEI_NA_EINAI_LARGE"
    ttl-minutes: 60